# By convention, a file containing both the delivery pipeline config and the target config is
# called clouddeploy.yaml, and a pipeline config without targets is called delivery-pipeline.yaml
# 1. targetId: is the metadata name property from target definations. as in target-list.yaml
# 2. profiles: a list of zero or more Skaffold profile names from skaffold.yaml, this let you vary
#    configuration between targets while using a single configuration file.
# 3. strategy.standard.verify: set to true verfy a GCD deployment, default false.
# 4. strategy.standard: default: standard. other option: canary.
# 5. targetId can be one multi-targets with mutiple child targets.

apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: test-cicd-2-pipeline
description: test project cicd pipeline
serialPipeline:
  stages:
  - targetId: staging
  - targetId: multi-prods
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: multi-prods
description: test for multiple prod clusters
multiTarget:
 targetIds: [ prod-us, prod-aust ]
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
description: testing development cluster
gke:
  cluster: projects/test-cicd-2/locations/us-central1/clusters/staging
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod-us
description: testing production cluster
gke:
  cluster: projects/test-cicd-2/locations/us-central1/clusters/prod-us
---

# even a GKE in different location, target need to be created in the same location with delivery-pipeline
# accoring to: https://cloud.google.com/deploy/docs/regions#:~:text=Google%20Cloud%20Deploy%20instances%20can,to%20deploy%20to%20multiple%20regions.
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod-aust
description: testing production cluster
gke:
  cluster: projects/test-cicd-2/locations/australia-southeast1/clusters/prod-aust
